CREATE TABLE SUDOKU_USUARIOS (
    GOOGLE_SUB VARCHAR2(255 CHAR) PRIMARY KEY,
    NOME VARCHAR2(120 CHAR) NOT NULL,
    FOTO_URL VARCHAR2(1000 CHAR),
    CRIADO_EM TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SUDOKU_PARTIDAS (
    ID VARCHAR2(36 CHAR) PRIMARY KEY,
    GOOGLE_SUB VARCHAR2(255 CHAR) NOT NULL,
    TAMANHO NUMBER(2) NOT NULL,
    DIFICULDADE VARCHAR2(10 CHAR) NOT NULL,
    INICIADA_EM TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    FINALIZADA_EM TIMESTAMP(6) WITH TIME ZONE,
    TEMPO_MS NUMBER(12),
    ERROS NUMBER(3) DEFAULT 0 NOT NULL,
    DICAS_USADAS NUMBER(1) DEFAULT 0 NOT NULL,
    VIDAS_EXTRAS NUMBER(3) DEFAULT 0 NOT NULL,
    RESULTADO VARCHAR2(12 CHAR) DEFAULT 'EM_ANDAMENTO' NOT NULL,
    CONSTRAINT FK_SUDOKU_PARTIDAS_USUARIOS FOREIGN KEY (GOOGLE_SUB)
        REFERENCES SUDOKU_USUARIOS (GOOGLE_SUB),
    CONSTRAINT CK_SUDOKU_TAMANHO CHECK (TAMANHO IN (4, 6, 9)),
    CONSTRAINT CK_SUDOKU_DIFICULDADE CHECK (DIFICULDADE IN ('facil', 'medio', 'dificil')),
    CONSTRAINT CK_SUDOKU_ERROS CHECK (ERROS >= 0),
    CONSTRAINT CK_SUDOKU_DICAS CHECK (DICAS_USADAS BETWEEN 0 AND 3),
    CONSTRAINT CK_SUDOKU_VIDAS CHECK (VIDAS_EXTRAS >= 0),
    CONSTRAINT CK_SUDOKU_TEMPO CHECK (TEMPO_MS IS NULL OR TEMPO_MS > 0),
    CONSTRAINT CK_SUDOKU_RESULTADO CHECK (
        RESULTADO IN ('EM_ANDAMENTO', 'VITORIA', 'DERROTA', 'ABANDONO')
    ),
    CONSTRAINT CK_SUDOKU_VITORIA CHECK (
        RESULTADO <> 'VITORIA' OR (FINALIZADA_EM IS NOT NULL AND TEMPO_MS IS NOT NULL)
    )
);

CREATE INDEX IX_SUDOKU_RANKING
    ON SUDOKU_PARTIDAS (TAMANHO, DIFICULDADE, RESULTADO, DICAS_USADAS, VIDAS_EXTRAS, TEMPO_MS);

CREATE INDEX IX_SUDOKU_PARTIDAS_USUARIO
    ON SUDOKU_PARTIDAS (GOOGLE_SUB);
